### ISSUE TITLE
when we can see source of POC

### ISSUE THREAD

**Issue by ghost** [vanhoefm/krackattacks#15]
hi, when we can see source of POC

**Comment by iWhacko** [comment]
Literally from the website:
"
# TOOLS
We have made scripts to detect whether an implementation of the 4-way handshake, group key handshake, or Fast BSS Transition (FT) handshake is vulnerable to key reinstallation attacks. These scripts will be released once we had the time to clean up their usage instructions.

We also made a proof-of-concept script that exploits the all-zero key (re)installation present in certain Android and Linux devices. This script is the one that we used in the demonstration video. It will be released once everyone had a reasonable chance to update their devices (and we have had a chance to prepare the code repository for release). We remark that the reliability of our proof-of-concept script may depend on how close the victim is to the real network. If the victim is very close to the real network, the script may fail because the victim will always directly communicate with the real network, even if the victim is (forced) on a different Wi-Fi channel than this network."

**Comment by 0ki** [comment]
Still, is there a timeline attached to these conditions? I'm ready to reimplement the attack from the info laid out in the paper, but it would be a waste of time if it's gonna be published soon(ish) anyway.
