### ISSUE TITLE
Add a readme?

### ISSUE THREAD

**Issue by Aditya94A** [vanhoefm/krackattacks#17]

**Comment by westurner** [comment]
You can actually now just create an ``index.md``:
https://github.com/blog/2289-publishing-with-github-pages-now-as-easy-as-1-2-3

**Comment by westurner** [comment]
IDK if a symlink from README.md to index.md works or not?

**Comment by mwoolweaver** [comment]
symlink index.html -> readme.md?

**Comment by westurner** [comment]
On Monday, October 16, 2017, Michael Woolweaver <notifications@github.com>
wrote:

> symlink index.html -> readme.md?
>
That would show HTML source in the project description? Or raw markdown as
index.html?

To be clear, one markdown document (and optional Jekyll theme) could work
instead of both a README and an index.html (because of new-ish GitHub pages
features):


As it turns out, these symlinks aren't necessary because GitHub Pages will
generate the index.html from README.md or index.md (on push; when there's
not a `.nojekyll` file):
```
ln -s index.md README.md
# or
ln -s README.md index.md
```

With e.g. CloudFlare DNS, you can put HTTPS and HTTP STS on a custom domain
in front of a GitHub Pages site; and have two CDNs for your README.md.

**Comment by ctrlplusb** [comment]
Here you go: https://krackattacks.now.sh

**Comment by ctrlplusb** [comment]
FYI I set up the about to be hosted as a static site on zeit's now.  They give you free static site hosting that you can alias.  I'm happy to remove the alias if you'd like to create your own account and host it via the same alias.

https://zeit.co/

**Comment by ctrlplusb** [comment]
And just found the website. Removing... 😊

**Comment by vanhoefm** [comment]
Now the README should be a tad more fancy, and hopefully it's clear to just visit the website at https://www.krackattacks.com
